#database configuration
spring:
  datasource:
    username: root
    password: 123789_qwe
    url: jdbc:mysql://127.0.0.1:3306/honeyeye?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
  main:
    banner-mode: off

mybatis:
  mapper-locations: classpath:/mybatis/*Mapper.xml #Mapper.xml location
  type-aliases-package: com.ditecting.honeyeye.domain #mybatis entity scan packages


