#thymeleaf模板配置
spring.thymeleaf.prefix: classpath:/templates/
spring.thymeleaf.suffix: .html
spring.thymeleaf.mode: HTML5
spring.thymeleaf.encoding: UTF-8
#热部署文件，页面不产生缓存，及时更新
spring.thymeleaf.cache: false
spring.resources.chain.strategy.content.enabled: true
spring.resources.chain.strategy.content.paths: /**

pcap4j:
  extension:
    util:
      tsharkPath: G:\NETSCtools\Wireshark\tshark.exe

honeyeye:
  system:
    inputingMode: 2 # 1:capture, 2:load
    outputingMode: 2 # others:plugin, 1:transmission, 2:storage, 3: transmission and storage
  inputer:
    capturer:
      count: -1
      readTimeout: 60
      snaplen: 65536
      filter: #tcp port 80 and (dst 192.168.0.100 or src 192.168.0.100)
      interval: 2
      enableAutoFind: true
    loader:
      filePath: "G:\\NETSC\\tanZhen\\honeynet\\Modbus_dataset\\run11.pcap"
  listener:
    transmittingGrain: 0 # others:rawPacket, 1:packet, 2:flow, 3:session
    transmittingTimeout: 1  # in [s]
    outputtingGrain: 2 # others:rawPacket, 1:packet, 2:flow, 3:session
    outputtingTimeout: 5  # in [s]
    pluginGrain: 0 # others:rawPacket, 1:packet, 2:flow, 3:session
    pluginTimeout: 1  # in [s]
    meetingTimeout: 10 # in [s]
    segmentMax: 10000
    transmittingListener:
      port: 5150
      netAddress:  192.168.0.1
  outputer:
    filePath: "G:\\NETSC\\tanZhen\\honeynet\\storage\\"
    fileName: "th1"

#不限制文件上传的大小
spring:
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1
