spring:
  datasource:
    url: jdbc:mysql://localhost:3306/honeyeye?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

# 搞个对象试试
star:
  name: Kobe
  content: China